### ISSUE TITLE
Installation of cbor2 5.2.0 on Python 2 fails

### ISSUE THREAD

**Issue by exarkun** [agronholm/cbor2#124]
cbor2 5.2.0 is documented as the last version of cbor2 supporting Python 2.  However, it fails to install on Python 2.7:

```
2021-12-22T15:24:30.9292547Z     Running setup.py (path:c:\users\runner~1\appdata\local\temp\pip-install-ochdzc\cbor2\setup.py) egg_info for package cbor2
2021-12-22T15:24:30.9293817Z     Created temporary directory: c:\users\runner~1\appdata\local\temp\pip-pip-egg-info-t6hesw
2021-12-22T15:24:30.9294536Z     Running command python setup.py egg_info
2021-12-22T15:24:32.2988482Z     c:\users\runner~1\appdata\local\temp\pip-install-ochdzc\cbor2\setup.py:11: UserWarning: Support for Python<3.6 will be dropped with cbor2 version 6.0.0
2021-12-22T15:24:32.2992141Z       warnings.warn("Support for Python<3.6 will be dropped with cbor2 version 6.0.0")
2021-12-22T15:24:32.2993054Z     Traceback (most recent call last):
2021-12-22T15:24:32.2994832Z       File "<string>", line 1, in <module>
2021-12-22T15:24:32.2995993Z       File "c:\users\runner~1\appdata\local\temp\pip-install-ochdzc\cbor2\setup.py", line 78, in <module>
2021-12-22T15:24:32.2996843Z         **kwargs
2021-12-22T15:24:32.2997825Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\__init__.py", line 144, in setup
2021-12-22T15:24:32.2998818Z         _install_setup_requires(attrs)
2021-12-22T15:24:32.2999982Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
2021-12-22T15:24:32.3001061Z         dist.fetch_build_eggs(dist.setup_requires)
2021-12-22T15:24:32.3002144Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\dist.py", line 719, in fetch_build_eggs
2021-12-22T15:24:32.3003137Z         replace_conflicting=True,
2021-12-22T15:24:32.3004320Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
2021-12-22T15:24:32.3005344Z         replace_conflicting=replace_conflicting
2021-12-22T15:24:32.3006415Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
2021-12-22T15:24:32.3007404Z         return self.obtain(req, installer)
2021-12-22T15:24:32.3008465Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
2021-12-22T15:24:32.3009413Z         return installer(requirement)
2021-12-22T15:24:32.3010455Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
2021-12-22T15:24:32.3011411Z         return cmd.easy_install(req)
2021-12-22T15:24:32.3012487Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
2021-12-22T15:24:32.3013650Z         return self.install_item(spec, dist.location, tmpdir, deps)
2021-12-22T15:24:32.3014859Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
2021-12-22T15:24:32.3015976Z         dists = self.install_eggs(spec, download, tmpdir)
2021-12-22T15:24:32.3017107Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
2021-12-22T15:24:32.3018268Z         return self.build_and_install(setup_script, setup_base)
2021-12-22T15:24:32.3019452Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
2021-12-22T15:24:32.3020552Z         self.run_setup(setup_script, setup_base, args)
2021-12-22T15:24:32.3021773Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
2021-12-22T15:24:32.3022799Z         run_setup(setup_script, args)
2021-12-22T15:24:32.3023813Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
2021-12-22T15:24:32.3024707Z         raise
2021-12-22T15:24:32.3025525Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\contextlib.py", line 35, in __exit__
2021-12-22T15:24:32.3026458Z         self.gen.throw(type, value, traceback)
2021-12-22T15:24:32.3027560Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
2021-12-22T15:24:32.3028376Z         yield
2021-12-22T15:24:32.3029081Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\contextlib.py", line 35, in __exit__
2021-12-22T15:24:32.3029870Z         self.gen.throw(type, value, traceback)
2021-12-22T15:24:32.3030822Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
2021-12-22T15:24:32.3031652Z         saved_exc.resume()
2021-12-22T15:24:32.3032498Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 141, in resume
2021-12-22T15:24:32.3033332Z         six.reraise(type, exc, self._tb)
2021-12-22T15:24:32.3034239Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
2021-12-22T15:24:32.3035034Z         yield saved
2021-12-22T15:24:32.3035854Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
2021-12-22T15:24:32.3036635Z         yield
2021-12-22T15:24:32.3037441Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
2021-12-22T15:24:32.3050299Z         _execfile(setup_script, ns)
2021-12-22T15:24:32.3051852Z       File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\setuptools\sandbox.py", line 44, in _execfile
2021-12-22T15:24:32.3052811Z         code = compile(script, filename, 'exec')
2021-12-22T15:24:32.3055969Z       File "c:\users\runner~1\appdata\local\temp\easy_install-8atejp\setuptools_scm-6.3.2\setup.py", line 22
2021-12-22T15:24:32.3056867Z         f"{type(self).__name__} is forbidden, "
2021-12-22T15:24:32.3057393Z                                               ^
2021-12-22T15:24:32.3057892Z     SyntaxError: invalid syntax
```

Seemingly because it `setup_requires` `setuptools_scm > 1.7.0` and setuptools_scm has made a number of Python 2-incompatible releases (probably after cbor2 5.2.0) that are > 1.7.0.  The setuptools_scm releases are marked as Python 3-only so I suppose that `setup_requires` requirements don't have that piece of metadata checked when choosing a candidate version.

I was able to work-around this by pre-installing a Python 2 compatible version of setuptools_scm (I picked 1.17 but there are probably newer compatible versions).  This isn't a great solution because it requires extra steps outside of the normal process / tooling to be able to install cbor2 (so, while I can easily type this into my terminal, it's harder to update all of the pieces of CI and packaging automation that are also affected).

A cbor2 5.2.1 release that pins a low-enough `setuptools_scm` upper bound (some further testing suggests `<6.0.0` is reasonable) would be a great help.

I am aware that Python 2 is long-since EOL and cbor2 itself doesn't even support Python 2 in new releases.  I encountered this cbor2 problem when upgrading one of my dependencies from a Python 2-only release to its first Python 3 compatible release.  That is a first step to being able to update my own codebase to be Python 3 compatible and then switch to Python 3.  If I can't upgrade that dependency on Python 2 then I have to mix all of those upgrade changes together with all of my own Python 3 porting changes ... which I would love to avoid.

**Comment by exarkun** [comment]
I created [a branch](https://github.com/PrivateStorageio/cbor2/tree/release-5.2) starting from the 5.2.0 release tag and adding just the new setuptools_scm constraint.

There is no appropriate branch for a PR to target though... And there's no CI configuration in the 5.2.0 tag, but presumably none of the *Python* in the project is broken by the new constraint.  I'm not sure what the next step is though.  Do a release?

**Comment by agronholm** [comment]
@Sekenre I'm okay with making a 5.2.0.post1 release with this change. If you don't object, I can handle it.

**Comment by Sekenre** [comment]
Always happy to keep things working on 2.7 as long as there's minimal changes. Like i don't want to be backporting new features.

**Comment by agronholm** [comment]
Yeah, this just involves modifying the `setuptools_scm` requirement so that it still works on Python 2.

**Comment by agronholm** [comment]
@exarkun All done, 5.2.0.post1 released.

**Comment by exarkun** [comment]
This is working with my CI configuration now.  Thank you both for such a quick turnaround.
