### ISSUE TITLE
cbor2 install on Python 3.10

### ISSUE THREAD

**Issue by inathanb6** [agronholm/cbor2#125]
Is cbor2 not working on 3.10? Getting the following when trying to install it: 

`ERROR: Could not build wheels for cbor2, which is required to install pyproject.toml-based projects`

Here is the full output

```
pip3 install cbor2
Collecting cbor2
  Using cached cbor2-5.4.2.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cbor2
  Building wheel for cbor2 (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\****\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\****\AppData\Local\Temp\tmph1x6093b'
       cwd: C:\Users\****\AppData\Local\Temp\pip-install-329fy66a\cbor2_fe3830c11cc841dabd70671ef66bc919
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\cbor2
  copying cbor2\decoder.py -> build\lib.win-amd64-3.10\cbor2
  copying cbor2\encoder.py -> build\lib.win-amd64-3.10\cbor2
  copying cbor2\tool.py -> build\lib.win-amd64-3.10\cbor2
  copying cbor2\types.py -> build\lib.win-amd64-3.10\cbor2
  copying cbor2\__init__.py -> build\lib.win-amd64-3.10\cbor2
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 67, in <module>
      setup(
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\****\AppData\Local\Temp\pip-build-env-dz6gave2\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cbor2
Failed to build cbor2
ERROR: Could not build wheels for cbor2, which is required to install pyproject.toml-based projects
```

Tried fresh installing 3.10 and still have the same issue, started happening after going from 3.9 to 3.10

Thanks

**Comment by agronholm** [comment]
You're lacking a compiler which is required to build C extensions which this library contains. Usually a wheel would be provided but no releases have been done since the CI configuration was updated to generate them. A post-release would fix that. @Sekenre would it be alright to push a post-release, with the appropriate changes to GA config that would allow such tags?

**Comment by Sekenre** [comment]
Absolutely, it won't conflict with anything I'm doing.

**Comment by agronholm** [comment]
After some tweaking, I managed to get the configuration right, but the macOS wheel creation job timed out after 2 hours. I'm trying again, but if the result is the same, I will have to exclude macOS from the process.

**Comment by agronholm** [comment]
Good news: the job completed successfully, so we have a large array of binary wheels available now: https://pypi.org/project/cbor2/#files

**Comment by agronholm** [comment]
I'm also looking into building Linux ARM binaries by leveraging Qemu. The cibuildwheel docs have an [easy looking example](https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation).
