### ISSUE TITLE
Cannot decode datetime objects

### ISSUE THREAD

**Issue by podshumok** [agronholm/cbor2#3]
Here is a traceback:
```
Python 3.5.0+ (default, Oct 11 2015, 09:05:38) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cbor2
>>> import datetime
>>> cbor2.loads(cbor2.dumps({1: [], '1': {}, 0: datetime.datetime.now(datetime.timezone.utc)}))
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 304, in decode
    return decoder(self, subtype, fp, shareable_index)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 153, in decode_semantic
    return decoder(self, value, fp, shareable_index)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 175, in decode_datetime_string
    microsecond, tz)
OverflowError: signed integer is greater than maximum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 322, in loads
    return decoder.decode(buf)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 304, in decode
    return decoder(self, subtype, fp, shareable_index)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 144, in decode_semantic
    return self.decode(fp, shareable_index)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 304, in decode
    return decoder(self, subtype, fp, shareable_index)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 131, in decode_map
    value = self.decode(fp)
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/decoder.py", line 308, in decode
    raise CBORDecodeError('error decoding value at index {}: {}'.format(fp.tell(), e))
cbor2.decoder.CBORDecodeError: error decoding value at index 34: signed integer is greater than maximum
```

Version:
cbor2==3.0.1

**Comment by agronholm** [comment]
Thanks for reporting! This somehow slipped through the cracks.

**Comment by podshumok** [comment]
Stil broken :( This time - encoder.
```
Python 3.5.0+ (default, Oct 11 2015, 09:05:38)·                                                                                                 
[GCC 5.2.1 20151010] on linux                                                                                                                   
Type "help", "copyright", "credits" or "license" for more information.                                                                          
>>> import cbor2                                                                                                                                
>>> import datetime                                                                                                                             
>>> cbor2.loads(cbor2.dumps([b'abc', 'def\n', 1, {1.0: {}}, (), None, float('nan'), datetime.datetime.now(datetime.timezone.utc)]))             
Traceback (most recent call last):                                                                                                              
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 283, in encode                                                            
    encoder = self.encoders[obj_type]                                                                                                           
KeyError: <class 'datetime.datetime'>                                                                                                           
                                                                                                                                                
During handling of the above exception, another exception occurred:                                                                             
                                                                                                                                                
Traceback (most recent call last):                                                                                                              
  File "<stdin>", line 1, in <module>                                                                                                           
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 311, in dumps                                                             
    CBOREncoder(**kwargs).encode(obj, buf)                                                                                                      
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 297, in encode                                                            
    encoder(self, obj, fp)                                                                                                                      
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 52, in wrapper                                                            
    func(encoder, value, fp, *args, **kwargs)                                                                                                   
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 138, in encode_array                                                      
    self.encode(item, fp)                                                                                                                       
  File "/tmp/venv/lib/python3.5/site-packages/cbor2/encoder.py", line 291, in encode                                                            
    if issubclass(obj_type, type_):                                                                                                             
TypeError: issubclass() arg 2 must be a class or tuple of classes                                                                               

```

**Comment by agronholm** [comment]
Fixed again, hopefully all good now!

**Comment by podshumok** [comment]
Thanks@
